### ISSUE TITLE
/kernel_require.rb: 59:in require: cannot load such file - client 

### ISSUE THREAD

**Issue by Labs22** [picatz/shodanz#11]
So I'm working with ruby api for future project.
And I've made like this.
I know there's a Client.rb file inside of the default folder  so I've made a require for  it.
and give me that issue.
Without hte client lib  the script don't give me any result and the script back to the console
I' guess I'll have to add json and another lib right?

I'll stay here working on script at all night if I fix it I'll update but so far no luck
PS: I'll make the code of ruby looks better at future but I'm new on ruby so is not perfect code.
Ps 2: I don't want you to make that job I need just a direction.
Have niice night.

```
require "shodanz"
require "client"
def shodanz

```
```
if shodanz.client.new("MyAPI")
  puts shodanz.client.new
if endendendclient.rest_api.host
  puts endendendclient.rest_api.host_search
if client.rest_api.host("8.8.8.8", history: true) 
   puts client.rest_api.host_search
if client.rest_api.host_search("mongodb")
   puts client.rest_api.host_search
if client.rest_api.host_search("nginx")
   puts client.rest_api.host_search
if client.rest_api.host_search("apache", after: "1/12/16")
  puts client.rest_api.host_search
if client.rest_api.host_search("ssh", port: 22, page: 1)
  pits client.rest_api.host_search
if client.rest_api.host_search("ssh", port: 22, page: 2)
   puts client.rest_api.host_search
if client.rest_api.host_search("ftp", port: 21, facets: { link: "Ethernet or modem" })
   puts clients.rest_ap
```

Issue:
```
traceback (most recent call last):
	2: from shodanz.rb:2:in `<main>'
	1: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
/usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require': cannot load such file -- client (LoadError)
```

```

**Comment by picatz** [comment]
@Labs22 Hello 👋 

I'd love to help you get started. 

Could you share the full ruby script that isn't outputting anything to the console? 

Otherwise, this might help: if you want to print information to [STDOUT](https://en.wikipedia.org/wiki/Standard_streams#Standard_output_(stdout)) in ruby, you usually use [`puts`](https://learnrubythehardway.org/book/ex5.html).

### Example
```ruby
require "shodanz"

# create client to talk to the API
client = Shodanz.client.new(key: "YOUR_API_KEY")

# perform a host search
# https://api.shodan.io/shodan/host/search
result = client.rest_api.host_search("nginx")

# print result of the host search to STDOUT
puts result
```

**Comment by Labs22** [comment]
@picatz  here is my ruby script:

```
require 'unirest'
require 'oj'
require 'shodanz/version'
require 'shodanz/api'
require 'shodanz/client'

def shodanz

if shodanz.client.new("MyKey")
  puts shodanz.client.new
if endendendclient.rest_api.host("8.8.8.8")# Default
  puts endendendclient.rest_api.host_search
if client.rest_api.host("8.8.8.8", history: true) # All historical banners should be returned.
   puts client.rest_api.host_search
if client.rest_api.host_search("mongodb")
   puts client.rest_api.host_search
if client.rest_api.host_search("nginx")
   puts client.rest_api.host_search
if client.rest_api.host_search("apache", after: "1/12/16")
  puts client.rest_api.host_search
if client.rest_api.host_search("ssh", port: 22, page: 1)
  pits client.rest_api.host_search
if client.rest_api.host_search("ssh", port: 22, page: 2)
   puts client.rest_api.host_search
if client.rest_api.host_search("ftp", port: 21, facets: { link: "Ethernet or modem" })
   puts clients.rest_api.host_search
end
end
end
end
end
end
end
end
end
end
```

**Comment by picatz** [comment]
@Labs22 The reason you're seeing no output when you run your script is because it's only defining a `shodan` method (which is much easier to see with proper indentation and syntax hilighting):
```ruby
require 'unirest'
require 'oj'
require 'shodanz/version'
require 'shodanz/api'
require 'shodanz/client'

def shodanz
  if shodanz.client.new("MyKey")
    puts shodanz.client.new
    if endendendclient.rest_api.host("8.8.8.8")# Default
      puts endendendclient.rest_api.host_search
      if client.rest_api.host("8.8.8.8", history: true) # All historical banners should be returned.
        puts client.rest_api.host_search
        if client.rest_api.host_search("mongodb")
          puts client.rest_api.host_search
          if client.rest_api.host_search("nginx")
            puts client.rest_api.host_search
            if client.rest_api.host_search("apache", after: "1/12/16")
              puts client.rest_api.host_search
              if client.rest_api.host_search("ssh", port: 22, page: 1)
                pits client.rest_api.host_search
                if client.rest_api.host_search("ssh", port: 22, page: 2)
                  puts client.rest_api.host_search
                  if client.rest_api.host_search("ftp", port: 21, facets: { link: "Ethernet or modem" })
                    puts clients.rest_api.host_search
                  end
                end
              end
            end
          end
        end
      end
    end
  end
end
```

However, you shouldn't need to do this, and `shodan` method you're trying to define and use won't be useful to you since it's not using `shodanz`/ruby correctly. This is very common for beginners, do don't worry! 👍 

## Working Example
You should only need to require `shodanz` for your script to work, which I've modified like so:
```ruby
require 'shodanz'

client = Shodanz.client.new(key: "YOUR_KEY_HERE")

puts "Search results for 8.8.8.8:"
puts client.rest_api.host("8.8.8.8")

puts "Search results for 8.8.8.8, with history:"
puts client.rest_api.host("8.8.8.8", history: true)

puts "Search results for mongodb:"
puts client.rest_api.host_search("mongodb")

puts "Search results for nginx:"
puts client.rest_api.host_search("nginx")

puts "Search results for apache, after 1/12/16:"
puts client.rest_api.host_search("apache", after: "1/12/16")

puts "Search results for ssh, on port 22, page 1:"
puts client.rest_api.host_search("ssh", port: 22, page: 1)

puts "Search results for ssh, on port 22, page 2:"
puts client.rest_api.host_search("ssh", port: 22, page: 2)

puts "Search results for ftp, on port 21, using facets:"
puts client.rest_api.host_search("ftp", port: 21, facets: { link: "Ethernet or modem" })
```

Please feel free to let me know of any other issues you have! 🙏
