### ISSUE TITLE
`client.api_rest.my_ip` not working

### ISSUE THREAD

**Issue by emiliska** [picatz/shodanz#5]
The `client.rest_api.my_ip` function is not working due to a typo in the URL endpoint

```
irb(main):007:0> client.rest_api.my_ip
TypeError: exception class/object expected
        from /var/lib/gems/2.3.0/gems/shodanz-1.0.2/lib/shodanz/apis/rest.rb:180:in `raise'
        from /var/lib/gems/2.3.0/gems/shodanz-1.0.2/lib/shodanz/apis/rest.rb:180:in `get'
        from /var/lib/gems/2.3.0/gems/shodanz-1.0.2/lib/shodanz/apis/rest.rb:164:in `my_ip'
        from (irb):7
        from /usr/bin/irb:11:in `<main>'
```

Suggested Fix: Update endpoint URL in [shodanz/lib/shodanz/apis/rest.rb](https://github.com/picatz/shodanz/blob/master/lib/shodanz/apis/rest.rb)

**Comment by picatz** [comment]
Fixed with https://github.com/picatz/shodanz/pull/6
